# Generated by Django 4.0.4 on 2022-06-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_email_remove_cliente_imoveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='dataCadastro',
        ),
    ]
