# Generated by Django 4.0.4 on 2022-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_nome_cliente_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataCadastro',
            field=models.DateField(),
        ),
    ]
