# Generated by Django 4.0.4 on 2022-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDesocupacao', models.DateField()),
                ('periodo', models.DateField()),
                ('formaGarantia', models.CharField(max_length=255)),
                ('fiador', models.CharField(max_length=255)),
            ],
        ),
    ]
